# Generated by Django 4.1 on 2022-08-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=20)),
                ('restaurant_adress', models.TextField()),
            ],
        ),
    ]
