# Generated by Django 4.1 on 2022-09-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0006_alter_restaurant_restaurant_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=40)),
                ('dish_price', models.IntegerField()),
                ('dish_image', models.ImageField(upload_to='Item_images')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.restaurant')),
            ],
        ),
    ]
