# Generated by Django 4.1.1 on 2022-09-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0007_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('order_placed_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('orders', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.dish')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.restaurant')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
    ]
