# Generated by Django 4.1.1 on 2022-09-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0008_placeorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
    ]
