# Generated by Django 4.1.1 on 2022-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0009_placeorder_grand_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
