# Generated by Django 4.1.1 on 2022-09-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0010_delete_placeorder_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('order_placed_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('orders', models.CharField(max_length=1000)),
                ('grand_total', models.IntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
    ]
