# Generated by Django 4.1.1 on 2022-09-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0011_placeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dishes', models.ManyToManyField(to='ZomatoApp.dish')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PlaceOrder',
        ),
    ]
