# Generated by Django 4.1.1 on 2022-09-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0014_remove_order_cart_delete_cart_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.dish')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.cart')),
            ],
        ),
    ]
