# Generated by Django 4.1.1 on 2022-09-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0016_cart_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
