# Generated by Django 4.1.1 on 2022-09-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0017_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total_price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.cart')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
    ]
