# Generated by Django 4.1.1 on 2022-09-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0018_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
