# Generated by Django 4.1.1 on 2022-09-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0020_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
