# Generated by Django 4.1.1 on 2022-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0022_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='cart', related_query_name='cart_objects', to='ZomatoApp.cart'),
        ),
    ]
