# Generated by Django 4.1.1 on 2022-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0023_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
