# Generated by Django 4.1.1 on 2022-10-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZomatoApp', '0024_cart_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZomatoApp.customer')),
            ],
        ),
    ]
